In [1]:
import sys 
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0, .5, 1, 2, 2.5])

In [5]:
print(a)

[1 2 3 4]


In [6]:
print(b)

[0.  0.5 1.  2.  2.5]


In [7]:
a[0], a[1]

(1, 2)

In [11]:
a[0:]

array([1, 2, 3, 4])

In [12]:
a[1:3]

array([2, 3])

In [13]:
a[1:-1]

array([2, 3])

In [14]:
a[::2]

array([1, 3])

In [15]:
##Array types


In [18]:
a.dtype


dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [26]:

np.array([1, 2, 3, 4], dtype=float)


array([1., 2., 3., 4.])

In [27]:
## Dimensions and shapes


In [31]:
A = np.array([
    [1,2,3],
    [4,5,6]
]
)

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
A.shape

(2, 3)

In [34]:
A.ndim

2

In [35]:
A.size #total number of elements we have

6

In [46]:
B = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
]

)

In [47]:
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [48]:
B.shape

(3, 2, 3)

In [49]:
B.dtype

dtype('int32')

In [50]:
## Indexing and slicing of Matrices


In [51]:
A = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]       
)

In [52]:
A[1]

array([4, 5, 6])

In [53]:
A[0][1]

2

In [54]:
A[0:2]   #SPECIFIC ROWS YOU WANNA SHOW

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [60]:
A[1] = np.array([10,10,10])

In [61]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [62]:
A[2] = 99

In [63]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [64]:
A[:, 2:]

array([[ 3],
       [10],
       [99]])

In [65]:
#SUMMARY STATISTICS


In [66]:
a = np.array([1,2,3,4])

In [67]:
a.sum()

10

In [68]:
a.mean()

2.5

In [69]:
a.std()

1.118033988749895

In [70]:
a.var()

1.25

In [71]:
A = np.array(
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
    
    
]


)

In [72]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
A.mean()

5.0

In [74]:
A.std()

2.581988897471611

In [75]:
A.var()

6.666666666666667

In [76]:
A.sum()

45

In [77]:
A.sum(axis=0)   #column

array([12, 15, 18])

In [78]:
A.sum(axis=1) #row

array([ 6, 15, 24])

In [79]:
A.mean(axis = 1) #row

array([2., 5., 8.])

In [80]:
A.mean(axis=0) #column

array([4., 5., 6.])

In [81]:
A.std(axis=0) #column

array([2.44948974, 2.44948974, 2.44948974])

In [82]:
A.std(axis=1) #row

array([0.81649658, 0.81649658, 0.81649658])

In [83]:
#Broadcasting and Vectorizing operations


In [91]:
a = np.arange(10, 15,2)

In [92]:
a

array([10, 12, 14])

In [93]:
a = np.arange(4)

In [94]:
a

array([0, 1, 2, 3])

In [95]:
a + 10

array([10, 11, 12, 13])

In [96]:
a

array([0, 1, 2, 3])

In [97]:
a +=100


In [98]:
a

array([100, 101, 102, 103])

In [99]:
b = np.array([10,30,40,50])

In [100]:
a + b 

array([110, 131, 142, 153])

In [107]:
c = np.array([3, 4])


In [108]:
a + c

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [109]:
# Boolean arrays

In [110]:
a = np.arange(4)

In [111]:
a

array([0, 1, 2, 3])

In [115]:
a[[True, False, False, True]]     ##I don't really understand why double [] are there???????????????????

array([0, 3])

In [116]:
a >=2

array([False, False,  True,  True])

In [117]:
a[a>=2]

array([2, 3])

In [118]:
a.mean()

1.5

In [119]:
a>a.mean()

array([False, False,  True,  True])

In [120]:
a[a>a.mean()]

array([2, 3])

In [122]:
a[~(a > a.mean())]

array([0, 1])

In [124]:
a[(a % 2 == 0) & (a<=2)]

array([0, 2])

In [125]:
A = np.random.randint(100, size = (3,3))

In [126]:
A

array([[41, 50, 44],
       [71,  1, 65],
       [19,  5, 82]])

In [130]:
A[np.array(
    
    [
        [True, False, False],
        [False, False, True],
        [True, True, False]
    ]
    
)]

array([41, 65, 19,  5])

In [132]:
A[A>30]

array([41, 50, 44, 71, 65, 82])

In [133]:
A

array([[41, 50, 44],
       [71,  1, 65],
       [19,  5, 82]])

In [135]:
(A>30) & (A % 2 == 0)

array([[False,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [136]:



# LINEAR ALGEBRA


In [137]:
A = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
    
])

In [138]:
B = np.array(
[
        [6 , 5],
        [4 , 3],
        [2 , 1]
    
    
    
])

In [139]:
A.dot(B)

array([[[20, 14],
        [56, 41],
        [92, 68]]])

In [140]:
A @ B

array([[[20, 14],
        [56, 41],
        [92, 68]]])

In [141]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [143]:
A

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [142]:
B.T @ A

array([[[36, 48, 60],
        [24, 33, 42]]])

In [146]:
(B.T).dot(A)

array([[[36, 48, 60]],

       [[24, 33, 42]]])

In [148]:
####

In [147]:
####USEFUL NUMPY FUNCTIONS

In [151]:
np.random.random(size=2) ###uniform distribution

array([0.82427156, 0.13026289])

In [153]:
np.random.normal(size=2) # normal distribution with mean 0 and deviation 1

array([-0.54165751,  0.82580928])

In [154]:
np.random.rand(2,4)  #uniform with 4 columns and 2 rows

array([[0.81925566, 0.30909586, 0.56748778, 0.74389221],
       [0.05569923, 0.36084466, 0.01127632, 0.04263959]])

In [155]:
np.arange(0,1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [156]:
###

In [157]:
###RESHAPE 


In [158]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [159]:
#####LINSPACE

In [163]:
np.empty(7)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
       1.89146896e-307, 7.56571288e-307, 3.14082867e-317])